// Static, readable pages share the same project/service data as the homepage dialogs.
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json = value => JSON.stringify(value).replace(/</g, '\\u003c');
export function createContentPages({ write, data, services, config, source, localize }) {
  const styleVersion = createHash('sha256').update(readFileSync(new URL('../css/content-pages.css', import.meta.url), 'utf8').replace(/\r\n/g, '\n')).digest('hex').slice(0, 12);
  const origin = new URL(config.origin).origin;
  const pages = [];
  const symbols = source.match(/<svg class="icon-library"[\s\S]*?<\/svg>/)[0];
  const photoSwipe = source.match(/  <div class="pswp"[\s\S]*?(?=  <noscript>)/)[0];
  const titles = {
    websites: ['Создание сайтов на заказ','Custom website development'],
    webapps: ['Разработка веб-приложений','Web application development'],
    design: ['Дизайн сайтов и интерфейсов','Website and interface design'],
    seo: ['SEO и техническая оптимизация сайтов','SEO and technical website optimisation'],
    'social-design': ['Дизайн для социальных сетей','Social media design'],
    'full-cycle': ['Комплексная разработка цифровых проектов','Full-cycle digital development']
  };
  const icon = name => '<svg class="icon" aria-hidden="true"><use href="#i-' + esc(name) + '"></use></svg>';
  for (const language of ['ru','en']) {
    const ru = language === 'ru', base = config.languages[language], label = (a,b) => ru ? a : b;
    const text = (item,key) => !ru && item.en ? item.en[key] : item[key];
    const route = suffix => base + suffix;
    const projectPath = project => (data.projects.includes(project) ? 'work/' : 'personal/') + project.id + '/';
    const budget = project => Number.isFinite(project.budget)
      ? '<span class="detail-budget"><small>' + label('Бюджет','Budget') + '</small><strong>' + new Intl.NumberFormat(ru?'ru-RU':'en-US').format(project.budget) + ' ₽</strong></span>'
      : '<span class="investment">' + esc(text(project,'budgetNote') || label('Личный проект','Personal project')) + '</span>';
    const projectCard = project => '<a class="content-card project-link" href="' + route(projectPath(project)) + '"><img loading="lazy" src="/' + esc(project.image) + '" width="' + project.width + '" height="' + project.height + '" alt="' + esc(text(project,'title')) + '"><div><p class="eyebrow">' + esc(text(project,'label')) + '</p><h3>' + esc(text(project,'title')) + icon('arrow') + '</h3><p>' + esc(text(project,'description')) + '</p>' + budget(project) + '</div></a>';
    const serviceCard = service => '<a class="content-card service-link" href="' + route('services/'+service.id+'/') + '">' + icon(service.icon) + '<h3>' + esc(service[language].title) + icon('arrow') + '</h3><p>' + esc(service[language].intro) + '</p></a>';
    function document({suffix,title,description,body,crumbs=[],entity,image='/img/portfolio-social.jpg'}) {
      const url = origin + route(suffix);
      const alternates = Object.entries(config.languages).map(([lang,prefix])=>({language:lang,url:origin+prefix+suffix}));
      const breadcrumbs = [{name:label('Главная','Home'),url:origin+base},...crumbs.map(c=>({name:c.name,url:origin+route(c.suffix)})),{name:title,url}];
      const graph = [
        {'@type':'WebSite','@id':origin+'/#website',url:origin+'/',name:config.name},
        {'@type':'Person','@id':origin+'/#person',name:config.name,url:origin+'/'},
        {'@type':'WebPage','@id':url+'#page',url,name:title,description,inLanguage:language,isPartOf:{'@id':origin+'/#website'},...(entity?{mainEntity:{'@id':url+'#entity'}}:{})},
        {'@type':'BreadcrumbList',itemListElement:breadcrumbs.map((c,i)=>({'@type':'ListItem',position:i+1,name:c.name,item:c.url}))},
        ...(entity?[{...entity,'@id':url+'#entity',url}]:[])
      ];
      const head = '<meta name="description" content="'+esc(description)+'"><link rel="canonical" href="'+url+'">'+
        alternates.map(a=>'<link rel="alternate" hreflang="'+a.language+'" href="'+a.url+'">').join('')+
        '<link rel="alternate" hreflang="x-default" href="'+origin+config.languages[config.defaultLanguage]+suffix+'">'+
        '<meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:type" content="website"><meta property="og:site_name" content="'+esc(config.name)+'"><meta property="og:title" content="'+esc(title)+'"><meta property="og:description" content="'+esc(description)+'"><meta property="og:url" content="'+url+'"><meta property="og:locale" content="'+(ru?'ru_RU':'en_US')+'"><meta property="og:image" content="'+origin+image+'"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">'+json({'@context':'https://schema.org','@graph':graph})+'</script>';
      const html='<!doctype html><html lang="'+language+'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b1728"><title>'+esc(title)+' — '+esc(config.name)+'</title>'+head+'<link rel="icon" href="/img/atlas-favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/css/content-pages.css?v='+styleVersion+'"><link rel="stylesheet" href="/css/photoswipe.css"><link rel="stylesheet" href="/css/default-skin/default-skin.css"><script defer src="/js/photoswipe.js"></script><script defer src="/js/photoswipe-ui-default.js"></script><script defer src="/js/content-pages.js"></script></head><body>'+symbols+
        '<a class="skip-link" href="#content">'+label('К содержанию','Skip to content')+'</a><header class="content-header"><a class="identity" href="'+base+'"><img src="/img/atlas-favicon.svg" width="44" height="44" alt=""><span>Alexandr Azimov</span></a><nav aria-label="'+label('Навигация','Navigation')+'"><a href="'+route('work/')+'">'+label('Работы','Work')+'</a><a href="'+route('services/')+'">'+label('Услуги','Services')+'</a><a href="'+base+'#about">'+label('Обо мне','About')+'</a></nav><div class="page-languages" aria-label="'+label('Язык','Language')+'">'+alternates.map(a=>'<a href="'+a.url.replace(origin,'')+'" lang="'+a.language+'" hreflang="'+a.language+'"'+(a.language===language?' aria-current="page"':'')+'><svg aria-hidden="true" viewBox="0 0 60 40"><use href="#flag-'+a.language+'"></use></svg>'+ (a.language==='ru'?'RU':'EN')+'</a>').join('')+'</div></header>'+
        '<main id="content"><nav class="breadcrumbs" aria-label="'+label('Навигационная цепочка','Breadcrumbs')+'">'+breadcrumbs.map((c,i)=>i===breadcrumbs.length-1?'<span aria-current="page">'+esc(c.name)+'</span>':'<a href="'+c.url.replace(origin,'')+'">'+esc(c.name)+'</a><span aria-hidden="true">/</span>').join('')+'</nav>'+body+
        '<section class="contact-strip"><div><p class="eyebrow">'+label('ЕСТЬ ИДЕЯ?','HAVE AN IDEA?')+'</p><h2>'+label('Обсудим ваш проект','Let’s discuss your project')+'</h2><p>'+label('Расскажите о задаче, сроках и желаемом результате.','Tell me about your goals, timeline and expected result.')+'</p></div><div class="contact-links"><a class="primary" href="'+esc(data.contacts.telegram)+'" target="_blank" rel="noopener noreferrer">'+icon('telegram')+'Telegram'+icon('arrow')+'</a><a href="mailto:'+esc(data.contacts.email)+'">'+icon('mail')+esc(data.contacts.email)+'</a><a href="'+esc(data.contacts.vk)+'" target="_blank" rel="noopener noreferrer">'+icon('vk')+label('ВКонтакте','VK')+'</a></div></section></main><footer class="content-footer"><a href="'+base+'">© '+new Date().getFullYear()+' Alexandr Azimov</a><a href="'+route('services/')+'">'+label('Все услуги','All services')+'</a><a href="'+route('work/')+'">'+label('Все работы','All work')+'</a></footer>'+localize(photoSwipe,language)+'</body></html>';
      const file=route(suffix).slice(1)+'index.html';write(file,html);pages.push({file,route:route(suffix),suffix,language});
    }
    document({suffix:'services/',title:label('Разработка, дизайн и SEO','Development, design and SEO'),description:label('Создание сайтов, веб-приложений, дизайн интерфейсов и соцсетей, SEO и комплексная разработка. Услуги Alexandr Azimov.','Custom websites, web apps, interface and social media design, SEO and full-cycle development by Alexandr Azimov.'),body:'<header class="page-intro"><p class="eyebrow">'+label('НАПРАВЛЕНИЯ РАБОТЫ','WHAT I DO')+'</p><h1>'+label('От идеи до работающего проекта.','From an idea to a working project.')+'</h1><p class="lead">'+label('Можно начать с одной задачи или собрать несколько направлений в общий проект. Состав, сроки и стоимость согласуем после изучения ТЗ.','Start with a single task or combine several services into one project. Scope, timing and price follow the agreed specification.')+'</p></header><div class="content-grid">'+services.map(serviceCard).join('')+'</div>'});
    document({suffix:'work/',title:label('Работы и кейсы','Work and case studies'),description:label('Реальные проекты Alexandr Azimov: сайты компаний, личное портфолио и дизайн сообщества ВКонтакте. Задачи, решения, бюджеты и иллюстрации.','Real projects by Alexandr Azimov: company websites, a personal portfolio and VK community design. Briefs, decisions, budgets and images.'),body:'<header class="page-intro"><p class="eyebrow">'+label('ПРОЕКТЫ / ПОДБОРКА','PROJECTS / SELECTED WORK')+'</p><h1>'+label('Каждая работа — отдельная история.','Every project has a story.')+'</h1><p class="lead">'+label('От задачи и визуальной концепции до готового результата. Здесь — мой вклад, решения и реальные экраны проектов.','From the brief and visual concept to the finished result. Explore my role, design decisions and real project screens.')+'</p></header><div class="content-grid">'+data.projects.map(projectCard).join('')+'</div><section class=\"content-section\"><h2>'+label('Личные проекты','Personal projects')+'</h2><div class=\"content-grid\">'+data.personalProjects.filter(p=>p.caseStudy).map(projectCard).join('')+'</div></section>'});
    for(const service of services){
      const s=service[language],title=titles[service.id][ru?0:1];
      const related=data.projects.filter(p=>service.id==='social-design'?p.id==='grinity-vk':p.id!=='grinity-vk').slice(0,3);
      const body='<header class="page-intro service-intro"><span class="service-symbol">'+icon(service.icon)+'</span><p class="eyebrow">'+label('УСЛУГА','SERVICE')+'</p><h1>'+esc(title)+'</h1><p class="lead">'+esc(s.intro)+'</p><a class="primary" href="'+esc(data.contacts.telegram)+'" target="_blank" rel="noopener noreferrer">'+label('Обсудить задачу','Discuss your project')+icon('arrow')+'</a></header>'+
        '<section class="content-section"><h2>'+label('Что входит в работу','What the work includes')+'</h2><div class="decision-grid">'+s.includes.map((item,i)=>'<article class="content-card"><span class="step">0'+(i+1)+'</span><h3>'+esc(item.title)+'</h3><p>'+esc(item.text)+'</p></article>').join('')+'</div></section>'+
        '<section class="content-section split-section"><div><p class="eyebrow">'+label('РЕЗУЛЬТАТ','DELIVERABLES')+'</p><h2>'+label('Что вы получаете','What you receive')+'</h2><ul class="deliverables">'+s.deliverables.map(v=>'<li>'+esc(v)+'</li>').join('')+'</ul></div><aside class="content-card"><h2>'+label('С чего начать','Where to start')+'</h2><p>'+esc(s.start)+'</p><p class="fine-print">'+esc(s.note)+'</p></aside></section>'+
        '<section class="content-section terms-summary"><h2>'+label('Стоимость и порядок работы','Pricing and working terms')+'</h2><p>'+label('Стоимость и этапы определяем после изучения ТЗ. Работа начинается после подписания договора с согласованным ТЗ, 100% предоплаты и получения необходимых материалов и доступов.','Price and milestones follow a review of the brief. Work starts after the contract and specification are signed, 100% prepayment is received, and the necessary materials and access are provided.')+'</p><p>'+label('Несоответствия согласованному ТЗ исправляю. Новые идеи и расширение объёма обсуждаем отдельно; итерации дизайна и поддержку фиксируем до начала работ.','I correct deviations from the agreed specification. New ideas and scope changes are agreed separately; design iterations and support are defined before work starts.')+'</p><a class="text-link" href="'+base+'#about">'+label('Условия сотрудничества и шаблоны договоров','Working terms and contract templates')+icon('arrow')+'</a></section>'+
        '<section class="content-section"><h2>'+label('Примеры работ','Project examples')+'</h2><div class="content-grid">'+related.map(projectCard).join('')+'</div></section><section class="content-section"><h2>'+label('Другие направления','Other services')+'</h2><div class="related-links">'+services.filter(other=>other.id!==service.id).map(other=>'<a href="'+route('services/'+other.id+'/')+'">'+esc(other[language].title)+icon('arrow')+'</a>').join('')+'</div></section>';
      document({suffix:'services/'+service.id+'/',title,description:s.intro,body,crumbs:[{name:label('Услуги','Services'),suffix:'services/'}],entity:{'@type':'Service',name:title,description:s.intro,provider:{'@id':origin+'/#person'},areaServed:label('Россия и другие страны','Russia and other countries')}});
    }
    for(const project of [...data.projects,...data.personalProjects.filter(p=>p.caseStudy)]){
      const s=text(project,'caseStudy'), title=text(project,'title'), description=text(project,'description');
      const gallery=project.gallery.map((im,i)=>'<figure class="page-shot'+(im.mobile?' portrait':'')+'"><a data-gallery-image href="/'+esc(im.src)+'" data-width="'+im.width+'" data-height="'+im.height+'" aria-label="'+esc(label('Увеличить: ','Enlarge: ')+text(im,'title'))+'"><img src="/'+esc(im.preview||im.src)+'" width="'+(im.previewWidth||im.width)+'" height="'+(im.previewHeight||im.height)+'" alt="'+esc(text(im,'title'))+'" loading="lazy" decoding="async">'+icon('expand')+'</a><figcaption><h3>'+String(i+1).padStart(2,'0')+' · '+esc(text(im,'title'))+'</h3><p>'+esc(text(im,'caption'))+'</p><small>'+im.width+' × '+im.height+' px</small></figcaption></figure>').join('');
      const body='<header class="page-intro"><p class="eyebrow">'+esc(text(project,'label'))+'</p><div class="case-title-row"><h1>'+esc(title)+'</h1>'+budget(project)+'</div><p class="lead">'+esc(description)+'</p><div class="intro-actions"><a class="primary" href="#screens">'+label('Смотреть иллюстрации','View images')+icon('expand')+'</a><a class="text-link" href="'+base+'#'+(data.projects.includes(project)?'work':'personal')+'">'+label('К портфолио','Back to the portfolio')+icon('arrow')+'</a></div></header>'+
        '<img class="page-hero" src="/'+esc(project.image)+'" width="'+project.width+'" height="'+project.height+'" alt="'+esc(title)+'" fetchpriority="high">'+
        '<dl class="detail-facts"><div><dt>'+label('Мой вклад','My role')+'</dt><dd>'+esc(s.role)+'</dd></div><div><dt>'+label('Статус','Status')+'</dt><dd>'+esc(s.state)+'</dd></div></dl><ul class="tags">'+s.tags.map(tag=>'<li>'+esc(tag)+'</li>').join('')+'</ul>'+
        '<section class="content-section"><h2>'+label(s.concept?'Концепция':'Задача',s.concept?'Concept':'The brief')+'</h2><p class="body-lead">'+esc(s.brief)+'</p></section><section class="content-section"><h2>'+label('Решения','Decisions')+'</h2><div class="decision-grid">'+s.decisions.map((d,i)=>'<article class="content-card"><span class="step">0'+(i+1)+'</span><h3>'+esc(d.title)+'</h3><p>'+esc(d.text)+'</p></article>').join('')+'</div></section>'+
        (s.product?'<section class="content-section"><h2>'+esc(s.product.title)+'</h2><p>'+esc(s.product.text)+'</p><ol class="deliverables">'+s.product.steps.map(step=>'<li>'+esc(step)+'</li>').join('')+'</ol></section>':'')+
        '<section class="content-section" id="screens"><div class="section-title"><h2>'+label('Иллюстрации проекта','Project images')+'</h2><span>'+project.gallery.length+' '+label('изображений','images')+'</span></div><div class="shot-grid">'+gallery+'</div></section>'+
        (project.video?'<section class="content-section motion-section"><div><h2>'+esc(s.motion.title)+'</h2><p>'+esc(s.motion.text)+'</p></div><video controls playsinline muted preload="none" poster="/'+esc(project.video.poster)+'" width="'+project.video.width+'" height="'+project.video.height+'"><source src="/'+esc(project.video.src)+'" type="video/mp4"></video></section>':'')+
        '<section class="content-section result"><h2>'+label(s.concept?'Текущий этап':'Результат',s.concept?'Current stage':'The result')+'</h2><p>'+esc(s.result)+'</p>'+(project.url?'<a class="text-link" href="'+esc(project.url)+'" target="_blank" rel="noopener noreferrer">'+label('Открыть проект','Visit project')+icon('arrow')+'</a>':'')+'</section><section class="content-section"><h2>'+label('Другие работы','More work')+'</h2><div class="content-grid">'+data.projects.filter(p=>p!==project).slice(0,2).map(projectCard).join('')+'</div></section>';
      document({suffix:projectPath(project),title:label('Кейс: ', 'Case study: ')+title,description,body,crumbs:data.projects.includes(project)?[{name:label('Работы','Work'),suffix:'work/'}]:[],image:'/'+project.image,entity:{'@type':'CreativeWork',name:title,description,author:{'@id':origin+'/#person'},image:project.gallery.map(im=>origin+'/'+im.src),inLanguage:language}});
    }
  }
  return pages;
}
